# For detailed configuration documentation, visit:
# https://supabase.com/docs/guides/cli/config

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
schema_paths = "./supabase/migrations"

[realtime]
enabled = true
bind_address = "0.0.0.0"
port = 54323
dns_cache_max_age = 3600
max_concurrent_streams = 100

[studio]
enabled = true
port = 54324
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.image_transformation]
enabled = true

[storage.s3_buckets]
global_s3_enabled = false

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
enable_double_opt_in = false
cookie_key = "sb-token"
cookie_duration = 604800

[auth.email]
enable_signup = true
enable_confirmations = false
double_opt_in = false
template_paths = {}
otp_length = 6
sender = "noreply@localhost"

[auth.email.smtp]
enabled = false
host = ""
port = 587
user = ""
pass = ""
admin_email = ""
sender_name = ""

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }}"
test_otp = ""

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

[auth.hook]
custom_access_token_hook = { enabled = false, uri = "pg-functions://postgres/public/custom_access_token_hook" }
send_email_verification = { enabled = false, uri = "pg-functions://postgres/public/send_email_verification" }
send_sms_verification = { enabled = false, uri = "pg-functions://postgres/public/send_sms_verification" }

[auth.external]

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = false
verify_enabled = false

[analytics]
enabled = true
port = 54327
vector_port = 54328
backend = "postgres"
logflare_enabled = false

[experimental]
oriole_version = "1.1.0"
s3_host = ""
s3_region = ""
s3_access_key = ""
s3_secret_key = ""
